name: responsive_spacing
description: Make your app responsive & adaptive with dynamic margins, paddings, gutters, body-size & columns.
version: 0.2.2
homepage: https://www.thiele.dev
repository: https://github.com/AlexanderThiele/responsive_spacing
issue_tracker: https://github.com/AlexanderThiele/responsive_spacing/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
